server:
  port: 1109
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: iglesia-service
          uri: lb://iglesia-service
          predicates:
            - Path=/api/**
        - id: municipality-service
          uri: lb://municipality-service
          predicates:
            - Path=/municipality/**
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/security/**